export const formFields = {
  success: true,
  message: "Metrics fetched successfully",
  payload: {
    records: [
      {
        id: 1,
        name: "Total Earning",
        type: "CURRENCY",
        isCalculated: false,
        value1: null,
        operator: null,
        value2: null,
        createdBy: 2,
        companyId: 1,
        role: 5,
        status: "ACTIVE",
        deleted: false,
        createdAt: "2025-01-22T05:12:25.886Z",
        updatedAt: "2025-01-22T05:12:25.886Z",
      },
      {
        id: 2,
        name: "Show Rate",
        type: "PERCENTAGE",
        isCalculated: true,
        value1: null,
        operator: "/",
        value2: null,
        createdBy: 2,
        companyId: 1,
        role: 4,
        status: "ACTIVE",
        deleted: false,
        createdAt: "2025-01-22T06:24:54.103Z",
        updatedAt: "2025-01-22T06:24:54.103Z",
      },
      {
        id: 3,
        name: "Live Calls",
        type: "NUMBER",
        isCalculated: false,
        value1: null,
        operator: null,
        value2: null,
        createdBy: 2,
        companyId: 1,
        role: 4,
        status: "ACTIVE",
        deleted: false,
        createdAt: "2025-01-22T06:26:39.493Z",
        updatedAt: "2025-01-22T06:26:39.493Z",
      },
      {
        id: 4,
        name: "Rates",
        type: "PERCENTAGE",
        isCalculated: true,
        value1: "Live Calls",
        operator: "/",
        value2: "Scheduled Calls",
        createdBy: 2,
        companyId: 1,
        role: 4,
        status: "ACTIVE",
        deleted: false,
        createdAt: "2025-01-22T06:40:58.903Z",
        updatedAt: "2025-01-22T06:40:58.903Z",
      },
    ],
    totalRecords: 4,
    totalPages: 1,
    query: { companyId: 1 },
  },
};
